"""empty message

Revision ID: 1c29bed70ad5
Revises: 4af1f90bf6d6
Create Date: 2021-06-23 20:30:35.612895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c29bed70ad5'
down_revision = '4af1f90bf6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('age', sa.String(length=3), nullable=True),
    sa.Column('date_of_birth', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'revoked_tokens', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'revoked_tokens', type_='unique')
    op.drop_table('detections')
    op.drop_table('patients')
    # ### end Alembic commands ###
