"""empty message

Revision ID: a23cd9a76d4f
Revises: 7dd03a1b8a36
Create Date: 2021-07-07 23:53:25.015253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a23cd9a76d4f'
down_revision = '7dd03a1b8a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=160), nullable=False),
    sa.Column('detection', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('detections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('detection', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='detections_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detections_pkey'),
    sa.UniqueConstraint('id', name='detections_id_key')
    )
    op.drop_table('files')
    # ### end Alembic commands ###
